name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python setup.py build_ext --inplace
          
      - name: Test with unittest
        run: python -m unittest tests/unit.py
        
      - name: Submit to codecov
        if: ${{ matrix.python-version == "3.8" && matrix.os == "ubuntu-latest" }}
        run: |
          pip install coverage
          coverage run -m unittest tests/unit.py 
          bash <(curl -s https://codecov.io/bash)
